/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-10-21 00:48:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class examForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Exam Creation Page</title>\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\"\r\n");
      out.write("    />\r\n");
      out.write("   \r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    \r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&display=swap\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css_create/stylesC.css\" />\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css\"\r\n");
      out.write("    />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"#\">SmartExam</a>\r\n");
      out.write("      <button\r\n");
      out.write("        class=\"navbar-toggler\"\r\n");
      out.write("        type=\"button\"\r\n");
      out.write("        data-bs-toggle=\"collapse\"\r\n");
      out.write("        data-bs-target=\"#navbarNav\"\r\n");
      out.write("        aria-controls=\"navbarNav\"\r\n");
      out.write("        aria-expanded=\"false\"\r\n");
      out.write("        aria-label=\"Toggle navigation\"\r\n");
      out.write("      >\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <div\r\n");
      out.write("        class=\"collapse navbar-collapse justify-content-between\"\r\n");
      out.write("        id=\"navbarNav\"\r\n");
      out.write("      >\r\n");
      out.write("        <ul class=\"navbar-nav justify-content-center flex-grow-1 pe-3\">\r\n");
      out.write("          <li class=\"nav-item active\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"admindashboard.jsp\">Dashboard</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"#\">Exam Concerns</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"examForm.jsp\">Create Exam</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"#\">Results Publishing</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("        </ul>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"container my-5\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <!-- Left Side: Form -->\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("          <h2 class=\"mb-4\">Create an Exam</h2>\r\n");
      out.write("          \r\n");
      out.write("          <p>Fill in the details to create an exam for students.</p>\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          <form action=\"ExamInsertServlet\" method=\"POST\" id=\"exam-form\" onsubmit=\"return validateForm()\">\r\n");
      out.write("            \r\n");
      out.write("          \r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("             <label for=\"exam-title\" class=\"form-label\">Exam Title</label>\r\n");
      out.write("             <input\r\n");
      out.write("                type=\"text\"\r\n");
      out.write("                class=\"form-control\"\r\n");
      out.write("                id=\"exam-title\"\r\n");
      out.write("                name=\"Title\"\r\n");
      out.write("                placeholder=\"Enter exam title\"\r\n");
      out.write("                required\r\n");
      out.write("              />\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                  <label for=\"exam-date\" class=\"form-label\">Exam Date</label>\r\n");
      out.write("                  <input\r\n");
      out.write("                    type=\"date\"\r\n");
      out.write("                    class=\"form-control\"\r\n");
      out.write("                    id=\"exam-date\"\r\n");
      out.write("                    name=\"Date\"\r\n");
      out.write("                    required\r\n");
      out.write("                  />\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                  <label for=\"exam-time\" class=\"form-label\">Exam Time</label>\r\n");
      out.write("                  <input\r\n");
      out.write("                    type=\"time\"\r\n");
      out.write("                    class=\"form-control\"\r\n");
      out.write("                    id=\"exam-time\"\r\n");
      out.write("                    name=\"Time\"\r\n");
      out.write("                    required\r\n");
      out.write("                  />\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("              <label for=\"exam-duration\" class=\"form-label\">Exam Duration</label>\r\n");
      out.write("              <input\r\n");
      out.write("                type=\"number\"\r\n");
      out.write("                class=\"form-control\"\r\n");
      out.write("                id=\"exam-duration\"\r\n");
      out.write("                name=\"Duration\"\r\n");
      out.write("                placeholder=\"Enter duration in minutes\"\r\n");
      out.write("                required\r\n");
      out.write("              />\r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("          \r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("              <label for=\"num-participants\" class=\"form-label\">Number of Participants</label>\r\n");
      out.write("              <input\r\n");
      out.write("                type=\"number\"\r\n");
      out.write("                class=\"form-control\"\r\n");
      out.write("                id=\"num-participants\"\r\n");
      out.write("                name=\"TotalParticipants\"\r\n");
      out.write("                placeholder=\"Enter number of participants\"\r\n");
      out.write("                required\r\n");
      out.write("              />\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("          \r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("              <label for=\"num-questions\" class=\"form-label\">Number of Questions</label>\r\n");
      out.write("             <input\r\n");
      out.write("                type=\"number\"\r\n");
      out.write("                class=\"form-control\"\r\n");
      out.write("                id=\"num-questions\"\r\n");
      out.write("                name=\"TotalQuestions\"\r\n");
      out.write("                placeholder=\"Enter number of questions\"\r\n");
      out.write("                required\r\n");
      out.write("              />\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("          \r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("              <label for=\"num-questions\" class=\"form-label\">Quiz Password</label>\r\n");
      out.write("              <input\r\n");
      out.write("                type=\"password\"\r\n");
      out.write("                class=\"form-control\"\r\n");
      out.write("                id=\"q-password\"\r\n");
      out.write("                name=\"Password\"\r\n");
      out.write("                placeholder=\"Enter Quiz password\"\r\n");
      out.write("                required\r\n");
      out.write("              />\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("        		<label id=\"exam-paper\" class=\"form-label\">Upload Exam Paper (PDF only)</label>\r\n");
      out.write("        		<input\r\n");
      out.write("            type=\"file\"\r\n");
      out.write("            class=\"form-control\"\r\n");
      out.write("            id=\"exam-paper\"\r\n");
      out.write("            name=\"paperFile\"\r\n");
      out.write("            accept=\".pdf\"\r\n");
      out.write("            required\r\n");
      out.write("        			/>\r\n");
      out.write("    			</div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"btn-container mt-4\">\r\n");
      out.write("              <input\r\n");
      out.write("                type=\"submit\"\r\n");
      out.write("                value=\"Submit\"\r\n");
      out.write("                id=\"add-question-btn\"\r\n");
      out.write("                class=\"button-35\"\r\n");
      out.write("                role=\"button\"\r\n");
      out.write("              />\r\n");
      out.write("          \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("      </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-6 image-container\">\r\n");
      out.write("          <img src=\"images/exam.jpg\" alt=\"Exam Image\" class=\"img-fluid\" />\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("	<script>\r\n");
      out.write("	 // Prevent past dates from being selected\r\n");
      out.write("    window.onload = function() {\r\n");
      out.write("      var examDate = document.getElementById(\"exam-date\");\r\n");
      out.write("      var today = new Date().toISOString().split('T')[0];\r\n");
      out.write("      examDate.setAttribute('min', today);\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    // Validate form before submission\r\n");
      out.write("    function validateForm() {\r\n");
      out.write("      var duration = document.getElementById(\"exam-duration\").value;\r\n");
      out.write("      var participants = document.getElementById(\"num-participants\").value;\r\n");
      out.write("      var questions = document.getElementById(\"num-questions\").value;\r\n");
      out.write("\r\n");
      out.write("      // Check if any value is negative or zero\r\n");
      out.write("      if (duration <= 0) {\r\n");
      out.write("        alert(\"Exam duration must be a positive number.\");\r\n");
      out.write("        return false;\r\n");
      out.write("      }\r\n");
      out.write("      if (participants <= 0) {\r\n");
      out.write("        alert(\"Number of participants must be a positive number.\");\r\n");
      out.write("        return false;\r\n");
      out.write("      }\r\n");
      out.write("      if (questions <= 0) {\r\n");
      out.write("        alert(\"Number of questions must be a positive number.\");\r\n");
      out.write("        return false;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      return true;  // Allow form submission if validation passes\r\n");
      out.write("    }\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
