/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-10-20 11:52:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class examconcern_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write(" <link rel=\"shortcut icon\" href=\"concern.png\" />\r\n");
      out.write("<title>Exam Concerns</title>\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&display=swap\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    />\r\n");
      out.write("    <!-- Bootstrap Icons -->\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <style>\r\n");
      out.write("      body {\r\n");
      out.write("        font-family: Roboto Condensed;\r\n");
      out.write("        background-color: white;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("      }\r\n");
      out.write("      .form-control {\r\n");
      out.write("        border: 1px solid #686d76;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        padding: 12px;\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        background-color: #eeeeee; /* Matches background */\r\n");
      out.write("        color: #121212; /* Text color */\r\n");
      out.write("        transition: border-color 0.3s ease;\r\n");
      out.write("\r\n");
      out.write("        font-family: Roboto Condensed;\r\n");
      out.write("      }\r\n");
      out.write("      .form-control:focus {\r\n");
      out.write("        border-color: #000000; /* Change border to black on focus */\r\n");
      out.write("        box-shadow: none; /* Remove any default focus shadow */\r\n");
      out.write("        outline: none;\r\n");
      out.write("        background-color: #eeeeee;\r\n");
      out.write("\r\n");
      out.write("        font-family: Roboto Condensed;\r\n");
      out.write("      }\r\n");
      out.write("      .form-container {\r\n");
      out.write("        padding: 30px;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        background-color: transparent;\r\n");
      out.write("        box-shadow: none;\r\n");
      out.write("\r\n");
      out.write("        font-family: Roboto Condensed;\r\n");
      out.write("      }\r\n");
      out.write("      p {\r\n");
      out.write("        color: #000000;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("\r\n");
      out.write("        font-family: Roboto Condensed;\r\n");
      out.write("      }\r\n");
      out.write("      .form-content {\r\n");
      out.write("        padding: 40px;\r\n");
      out.write("        max-width: 500px;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        background-color: transparent;\r\n");
      out.write("\r\n");
      out.write("        font-family: Roboto Condensed;\r\n");
      out.write("      }\r\n");
      out.write("      .background-image {\r\n");
      out.write("        background-image: url(\"concern.jpg\");\r\n");
      out.write("        background-size: contain;\r\n");
      out.write("        background-repeat: no-repeat;\r\n");
      out.write("        background-position: center;\r\n");
      out.write("        width: 50%;\r\n");
      out.write("        height: 80vh;\r\n");
      out.write("      }\r\n");
      out.write("      .full-page {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("      }\r\n");
      out.write("      .form-title {\r\n");
      out.write("        color: #4a12a5;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("\r\n");
      out.write("        font-family: Roboto Condensed;\r\n");
      out.write("      }\r\n");
      out.write("      .form-group {\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("      }\r\n");
      out.write("      .button-35 {\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        background-color: transparent;\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        box-shadow: transparent 0 0 0 3px, rgba(18, 18, 18, 0.1) 0 6px 20px;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        color: #121212;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        display: inline-flex;\r\n");
      out.write("        flex: 1 1 auto;\r\n");
      out.write("        font-family: Roboto Condensed;\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        line-height: 1;\r\n");
      out.write("        margin: 10px;\r\n");
      out.write("        outline: none;\r\n");
      out.write("        padding: 1rem 1.2rem;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        transition: box-shadow 0.2s, -webkit-box-shadow 0.2s;\r\n");
      out.write("        white-space: nowrap;\r\n");
      out.write("        border: 0;\r\n");
      out.write("        -webkit-user-select: none;\r\n");
      out.write("        user-select: none;\r\n");
      out.write("        touch-action: manipulation;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .button-35:hover {\r\n");
      out.write("        box-shadow: #000000 0 0 0 3px, transparent 0 0 0 0;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      label {\r\n");
      out.write("        color: #000000;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        font-family: Roboto Condensed;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      @media (max-width: 992px) {\r\n");
      out.write("        .background-image {\r\n");
      out.write("          display: none;\r\n");
      out.write("        }\r\n");
      out.write("        .form-container {\r\n");
      out.write("          padding: 30px;\r\n");
      out.write("          border-radius: 8px;\r\n");
      out.write("          background-color: transparent;\r\n");
      out.write("          box-shadow: none;\r\n");
      out.write("\r\n");
      out.write("          font-family: Roboto Condensed;\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("      .form-select {\r\n");
      out.write("        border: 1px solid #6c757dcc;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        padding: 12px;\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        background-color: rgb(255, 255, 255); /* Matches background */\r\n");
      out.write("        color: #121212; /* Text color */\r\n");
      out.write("        transition: border-color 0.3s ease;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .form-select:focus {\r\n");
      out.write("        border-color: #000000; /* Change border to black on focus */\r\n");
      out.write("        box-shadow: none; /* Remove any default focus shadow */\r\n");
      out.write("        outline: none;\r\n");
      out.write("      }\r\n");
      out.write("      .navbar {\r\n");
      out.write("        margin: 10px 10px 10px;\r\n");
      out.write("        border-radius: 25px;\r\n");
      out.write("        background: #4a12a5;\r\n");
      out.write("        /*backdrop-filter: blur(10px);\r\n");
      out.write("  -webkit-backdrop-filter: blur(10px);*/\r\n");
      out.write("        box-shadow: 5px;\r\n");
      out.write("        border-bottom: none;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .navbar-nav .nav-item {\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        font-family: Roboto Condensed;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        margin-right: 20px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .navbar-brand {\r\n");
      out.write("        margin: 15px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: rgb(255, 255, 255);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .navbar-nav .nav-link {\r\n");
      out.write("        color: rgb(255, 255, 255);\r\n");
      out.write("        position: relative;\r\n");
      out.write("        padding-bottom: 5px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .navbar-nav .nav-link:hover {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .navbar-nav .nav-link::before {\r\n");
      out.write("        content: \"\";\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        width: 0;\r\n");
      out.write("        height: 2px;\r\n");
      out.write("        bottom: 0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        background-color: rgb(255, 255, 255);\r\n");
      out.write("        visibility: hidden;\r\n");
      out.write("        transition: all 0.3s ease-in-out;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .navbar-nav .nav-link:hover::before {\r\n");
      out.write("        visibility: visible;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("      }\r\n");
      out.write("      @media (max-width: 768px) {\r\n");
      out.write("        .navbar {\r\n");
      out.write("          padding: 0.5rem 1rem;\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .btn-outline-primary {\r\n");
      out.write("        border: 2px;\r\n");
      out.write("        border-radius: 50px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-family: Roboto Condensed;\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        color: rgb(0, 0, 0);\r\n");
      out.write("        border-color: rgb(255, 255, 255);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .btn-outline-primary:hover {\r\n");
      out.write("        background-color: rgb(16, 16, 16);\r\n");
      out.write("        color: #ffffff;\r\n");
      out.write("        transition: 0.3s;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"home2.jsp\">SmartExam</a>\r\n");
      out.write("      <button\r\n");
      out.write("        class=\"navbar-toggler\"\r\n");
      out.write("        type=\"button\"\r\n");
      out.write("        data-bs-toggle=\"collapse\"\r\n");
      out.write("        data-bs-target=\"#navbarNav\"\r\n");
      out.write("        aria-controls=\"navbarNav\"\r\n");
      out.write("        aria-expanded=\"false\"\r\n");
      out.write("        aria-label=\"Toggle navigation\"\r\n");
      out.write("      >\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <div\r\n");
      out.write("        class=\"collapse navbar-collapse justify-content-between\"\r\n");
      out.write("        id=\"navbarNav\"\r\n");
      out.write("      >\r\n");
      out.write("        <ul class=\"navbar-nav justify-content-center flex-grow-1 pe-3\">\r\n");
      out.write("          <li class=\"nav-item active\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"studentprofile.jsp\">Dashboard</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"#\">Exam Concerns</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"examwrite.jsp\">Write Exams</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"getResultServlet\">Results</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("        </ul>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"full-page\">\r\n");
      out.write("      <div class=\"form-container\">\r\n");
      out.write("        <div class=\"form-content\">\r\n");
      out.write("          <h2 class=\"form-title\">Report Exam Concern</h2>\r\n");
      out.write("          <p>\r\n");
      out.write("            Fill in the form below to submit your concern regarding the exam.\r\n");
      out.write("          </p>\r\n");
      out.write("\r\n");
      out.write("          <form>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <label for=\"yourName\" class=\"form-label\"\r\n");
      out.write("                >Your Name <span class=\"text-danger\">*</span></label\r\n");
      out.write("              >\r\n");
      out.write("              <input\r\n");
      out.write("                type=\"text\"\r\n");
      out.write("                class=\"form-control\"\r\n");
      out.write("                id=\"name\"\r\n");
      out.write("                placeholder=\"john\"\r\n");
      out.write("                required\r\n");
      out.write("              />\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <label for=\"emailAddress\" class=\"form-label\"\r\n");
      out.write("                >Your Email Address</label\r\n");
      out.write("              >\r\n");
      out.write("              <input\r\n");
      out.write("                type=\"email\"\r\n");
      out.write("                class=\"form-control\"\r\n");
      out.write("                id=\"emailAddress\"\r\n");
      out.write("                placeholder=\"example@example.com\"\r\n");
      out.write("                required\r\n");
      out.write("              />\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <label for=\"concern\" class=\"form-label\"\r\n");
      out.write("                >Concern Description</label\r\n");
      out.write("              >\r\n");
      out.write("              <textarea\r\n");
      out.write("                class=\"form-control\"\r\n");
      out.write("                id=\"concern\"\r\n");
      out.write("                rows=\"4\"\r\n");
      out.write("                placeholder=\"Describe your concern...\"\r\n");
      out.write("                required\r\n");
      out.write("              ></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"btn-container mt-4\">\r\n");
      out.write("              <button type=\"submit\" button class=\"button-35\" role=\"button\">\r\n");
      out.write("                <i class=\"bi bi-envelope-fill\"></i> Submit Concern\r\n");
      out.write("              </button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"background-image\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
