/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-10-20 11:54:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class examwrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"Assets/IMGS/home.png\" />\r\n");
      out.write("    <title>Exam Writing - SmartExam</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap and other resources -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link\r\n");
      out.write("    href=\"https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900&display=swap\"\r\n");
      out.write("    rel=\"stylesheet\"\r\n");
      out.write("  />\r\n");
      out.write("   \r\n");
      out.write("    <style>\r\n");
      out.write("            @import url(\"https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\");\r\n");
      out.write("\r\n");
      out.write(":root {\r\n");
      out.write("  --button: ;\r\n");
      out.write("  --back: ;\r\n");
      out.write("  --fColor: ;\r\n");
      out.write("  --heading: ;\r\n");
      out.write("  --bFonts: ;\r\n");
      out.write("  --forms: ;\r\n");
      out.write("}\r\n");
      out.write("html,\r\n");
      out.write("body {\r\n");
      out.write("\r\n");
      out.write("   background: #c9d6ff;\r\n");
      out.write("  background-repeat: no-repeat;\r\n");
      out.write("  background-size: cover;\r\n");
      out.write("  background-position: center;\r\n");
      out.write("  height: 100vh;\r\n");
      out.write("  margin: 10px;\r\n");
      out.write("\r\n");
      out.write("  margin: 0px;\r\n");
      out.write("}\r\n");
      out.write("a {\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  color: #000000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar {\r\n");
      out.write("  margin: 10px 10px 10px;\r\n");
      out.write("  border-radius: 25px;\r\n");
      out.write("  background: #4a12a5;\r\n");
      out.write("  /*backdrop-filter: blur(10px);\r\n");
      out.write("  -webkit-backdrop-filter: blur(10px);*/\r\n");
      out.write("  box-shadow: 5px;\r\n");
      out.write("  border-bottom: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav .nav-item {\r\n");
      out.write("  font-size: 1rem;\r\n");
      out.write("  font-family: Roboto Condensed;\r\n");
      out.write("  font-weight: 700;\r\n");
      out.write("  margin-right: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-brand {\r\n");
      out.write("  margin: 15px;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  color: rgb(255, 255, 255);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav .nav-link {\r\n");
      out.write("  color: rgb(255, 255, 255);\r\n");
      out.write("  position: relative;\r\n");
      out.write("  padding-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav .nav-link:hover {\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav .nav-link::before {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  width: 0;\r\n");
      out.write("  height: 2px;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  background-color: rgb(255, 255, 255);\r\n");
      out.write("  visibility: hidden;\r\n");
      out.write("  transition: all 0.3s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav .nav-link:hover::before {\r\n");
      out.write("  visibility: visible;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-outline-primary {\r\n");
      out.write("  border: 2px;\r\n");
      out.write("  border-radius: 50px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-family: Roboto Condensed;\r\n");
      out.write("  font-weight: 500;\r\n");
      out.write("  font-size: 1rem;\r\n");
      out.write("  color: rgb(0, 0, 0);\r\n");
      out.write("  border-color: rgb(255, 255, 255);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-outline-primary:hover {\r\n");
      out.write("  background-color: rgb(124, 39, 243);\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  transition: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-toggler-icon {\r\n");
      out.write("  background-image: url(\"data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba%28255, 255, 255, 1%29' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E\");\r\n");
      out.write("}\r\n");
      out.write(".modal-header,\r\n");
      out.write(".bg-primary {\r\n");
      out.write("  background: #6c757dcc;\r\n");
      out.write("}\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("  .navbar {\r\n");
      out.write("    padding: 0.5rem 1rem;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bg-image {\r\n");
      out.write("  background-size: cover;\r\n");
      out.write("  background-position: center;\r\n");
      out.write("  height: 100vh;\r\n");
      out.write("}\r\n");
      out.write(".container {\r\n");
      out.write(" \r\n");
      out.write("   box-shadow: 20px;\r\n");
      out.write("  border-bottom: 2px;\r\n");
      out.write("\r\n");
      out.write("  border-radius: 20px;\r\n");
      out.write("  background-color: #f4f4f4;\r\n");
      out.write("  backdrop-filter: blur(10px);\r\n");
      out.write("  -webkit-backdrop-filter: blur(10px);\r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write(".Hbtn {\r\n");
      out.write("  margin: 10px;\r\n");
      out.write("}\r\n");
      out.write("h2 {\r\n");
      out.write("  font-size: 2rem;\r\n");
      out.write(" padding-top: 20px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("}\r\n");
      out.write("header h1 {\r\n");
      out.write("  font-family: Roboto Condensed;\r\n");
      out.write("\r\n");
      out.write("  margin-top: 10px;\r\n");
      out.write("  color: rgb(0, 0, 0);\r\n");
      out.write("  font-size: 4rem;\r\n");
      out.write("  font-weight: 900;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("  header h1 {\r\n");
      out.write("    font-size: 2.5rem;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .btn-container .btn {\r\n");
      out.write("    font-family: Roboto Condensed;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("    padding: 8px 16px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".l-card {\r\n");
      out.write("  margin-right: 20px;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("	width: auto;\r\n");
      out.write("	min-width: 360px;\r\n");
      out.write("	max-width: 480px;\r\n");
      out.write("	height: auto;\r\n");
      out.write("	background: #f5f5f5;\r\n");
      out.write("	color: #4a12a5;\r\n");
      out.write("	padding: 50px;\r\n");
      out.write("	box-shadow: 0px 7px 24px rgba(100, 100, 100, 0.4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".l-card__text p {\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("	font-family: \"Vollkorn\", serif;\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("	color: #e415a6;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".l-card__text p::after {\r\n");
      out.write("	content: \"\\201D\";\r\n");
      out.write("	display: inline;\r\n");
      out.write("	color: #999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".l-card__text p::before {\r\n");
      out.write("	content: \"\\201C\";\r\n");
      out.write("	display: inline;\r\n");
      out.write("	color: #999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".l-card__user {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: row;\r\n");
      out.write("	padding-top: 24px;\r\n");
      out.write("	margin-top: 12px;\r\n");
      out.write("	/* border-top: 1px solid #c1c1c1; */\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write(".l-card__userImage {\r\n");
      out.write("	width: 42px;\r\n");
      out.write("	height: 42px;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".l-card__userImage img {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".l-card__userInfo {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	margin-left: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".l-card__userInfo span:nth-child(1) {\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	font-family: sans-serif;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	color: #3f3f55;\r\n");
      out.write("}\r\n");
      out.write(".l-card__userInfo span:nth-child(2) {\r\n");
      out.write("	color: #adada6;\r\n");
      out.write("	font-family: sans-serif;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	margin-top: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("  .why-section {\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ft {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  background-color: #4a12a5;\r\n");
      out.write("  color: rgb(255, 255, 255);\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("}\r\n");
      out.write(".para {\r\n");
      out.write("  font-family: system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto,\r\n");
      out.write("    Oxygen, Ubuntu, Cantarell, \"Open Sans\", \"Helvetica Neue\", sans-serif;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("  footer {\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-35 {\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  background-color: transparent;\r\n");
      out.write("  border-radius: 12px;\r\n");
      out.write("  box-shadow: transparent 0 0 0 3px, rgba(18, 18, 18, 0.1) 0 6px 20px;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  color: #121212;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  display: inline-flex;\r\n");
      out.write("  flex: 1 1 auto;\r\n");
      out.write("  font-family: Roboto Condensed;\r\n");
      out.write("  font-size: 1rem;\r\n");
      out.write("  font-weight: 700;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  line-height: 1;\r\n");
      out.write("  margin: 20px;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  padding: 1rem 1.2rem;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  transition: box-shadow 0.2s, -webkit-box-shadow 0.2s;\r\n");
      out.write("  white-space: nowrap;\r\n");
      out.write("  border: 0;\r\n");
      out.write("  -webkit-user-select: none;\r\n");
      out.write("  user-select: none;\r\n");
      out.write("  touch-action: manipulation;\r\n");
      out.write("  box-shadow: #000000 0 0 0 3px, transparent 0 0 0 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-35:hover {\r\n");
      out.write("  background-color: #4a12a5;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  box-shadow: none;\r\n");
      out.write("}\r\n");
      out.write(".footer-section {\r\n");
      out.write("  background: #070111;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  padding: 40px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dcontainer {\r\n");
      out.write("  width: 90%;\r\n");
      out.write("  max-width: 1200px;\r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-content {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: space-between;\r\n");
      out.write("  flex-wrap: wrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*.footer-logo img {\r\n");
      out.write("  max-width: 150px;\r\n");
      out.write("}*/\r\n");
      out.write("\r\n");
      out.write(".footer-links, .footer-contact, .footer-subscribe {\r\n");
      out.write("  flex: 1 1 25%; /* Flex-grow, flex-shrink, and flex-basis */\r\n");
      out.write("  margin: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-links h3,\r\n");
      out.write(".footer-contact h3,\r\n");
      out.write(".footer-subscribe h3 {\r\n");
      out.write("  margin-bottom: 15px;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-links h3::after,\r\n");
      out.write(".footer-contact h3::after,\r\n");
      out.write(".footer-subscribe h3::after {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  display: block;\r\n");
      out.write("  height: 2px;\r\n");
      out.write("  width: 50px;\r\n");
      out.write("  background: #ff5e14;\r\n");
      out.write("  margin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-links ul {\r\n");
      out.write("  list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-links ul li {\r\n");
      out.write("  margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-links ul li a {\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-links ul li a:hover {\r\n");
      out.write("  text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-contact p {\r\n");
      out.write("  margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-subscribe form {\r\n");
      out.write("  display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-subscribe input {\r\n");
      out.write("  flex: 1;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-subscribe button {\r\n");
      out.write("  background: #ff5e14;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  padding: 10px 15px;\r\n");
      out.write("  color: white;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-subscribe button:hover {\r\n");
      out.write("  background: #e05210;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-bottom {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("  border-top: 1px solid #373636;\r\n");
      out.write("  padding: 20px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-bottom p {\r\n");
      out.write("  margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-socials a {\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  margin: 0 10px;\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-socials a:hover {\r\n");
      out.write("  color: #ff5e14;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive Styles */\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("  .footer-content {\r\n");
      out.write("      flex-direction: column;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .footer-links,\r\n");
      out.write("  .footer-contact,\r\n");
      out.write("  .footer-subscribe {\r\n");
      out.write("      flex: 1 1 100%; /* Full width for small screens */\r\n");
      out.write("      text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .footer-bottom {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write(".form-control{\r\n");
      out.write("  width: 500px;\r\n");
      out.write("}\r\n");
      out.write(".timer{\r\n");
      out.write("  color: #e05210;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /* Your CSS remains the same */\r\n");
      out.write("        .container {\r\n");
      out.write("            margin-top: 50px;\r\n");
      out.write("        }\r\n");
      out.write("        .exam-timer {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .upload-section {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .upload-section label {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-custom {\r\n");
      out.write("            background-color: #4a12a5;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-custom:hover {\r\n");
      out.write("            background-color: #350d7d;\r\n");
      out.write("        }\r\n");
      out.write("        footer {\r\n");
      out.write("            margin-top: 50px;\r\n");
      out.write("        }\r\n");
      out.write("        .form-control{\r\n");
      out.write("            width: 450px;\r\n");
      out.write("        }\r\n");
      out.write("        .timer{\r\n");
      out.write("            color: #e05210;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"home2.jsp\">SmartExam</a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse justify-content-between\" id=\"navbarNav\">\r\n");
      out.write("            <ul class=\"navbar-nav justify-content-center flex-grow-1\">\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"studentprofile.jsp\">Dashboard</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"examconcern.jsp\">Exam Concerns</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"getResultServlet\">Results</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"examwrite.jsp\">Exams</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"aboutus2.jsp\">About Us</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("   <!-- Exam Writing Page Content -->\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("        <h2>Exam Writing</h2>\r\n");
      out.write("\r\n");
      out.write("        <!-- Download Section -->\r\n");
      out.write("        <div class=\"download-section \">\r\n");
      out.write("            <button id=\"downloadBtn\" class=\"button-35\">Download Exam Paper</button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Countdown Timer -->\r\n");
      out.write("        <div class=\"timer\" id=\"countdown\">Time Left: 02:00:00</div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Upload Section -->\r\n");
      out.write("        <div class=\"upload-section \">\r\n");
      out.write("            <label for=\"uploadFile\" class=\"form-label\">Upload Your Answer Paper (PDF):</label>\r\n");
      out.write("            <input type=\"file\" class=\"form-control\" id=\"uploadFile\" accept=\"application/pdf\" />\r\n");
      out.write("            <button class=\"button-35\">Submit Answers</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Modal for Quiz Password -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"passwordModal\" tabindex=\"-1\" aria-labelledby=\"passwordModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title\" id=\"passwordModalLabel\">Enter Quiz Password</h5>\r\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <label for=\"quizPassword\" class=\"form-label\">Quiz Password:</label>\r\n");
      out.write("                    <input type=\"password\" id=\"quizPassword\" class=\"form-control\" placeholder=\"Enter password\"  />\r\n");
      out.write("                    <small class=\"text-danger d-none\" id=\"errorMsg\">Incorrect Password, please try again!</small>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("                    <button type=\"button\" id=\"submitPassword\" class=\"btn btn-primary\">Submit</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("      let countdownInterval;\r\n");
      out.write("\r\n");
      out.write("      // Countdown function\r\n");
      out.write("      function startCountdown(duration) {\r\n");
      out.write("        let timer = duration, hours, minutes, seconds;\r\n");
      out.write("        countdownInterval = setInterval(function () {\r\n");
      out.write("          hours = Math.floor((timer / 3600) % 24);\r\n");
      out.write("          minutes = Math.floor((timer % 3600) / 60);\r\n");
      out.write("          seconds = Math.floor(timer % 60);\r\n");
      out.write("\r\n");
      out.write("          hours = hours < 10 ? \"0\" + hours : hours;\r\n");
      out.write("          minutes = minutes < 10 ? \"0\" + minutes : minutes;\r\n");
      out.write("          seconds = seconds < 10 ? \"0\" + seconds : seconds;\r\n");
      out.write("\r\n");
      out.write("          document.getElementById(\"countdown\").textContent = \"Time Left: \" + hours + \":\" + minutes + \":\" + seconds;\r\n");
      out.write("\r\n");
      out.write("          if (--timer < 0) {\r\n");
      out.write("            clearInterval(countdownInterval);\r\n");
      out.write("            document.getElementById(\"countdown\").textContent = \"Time's Up!\";\r\n");
      out.write("          }\r\n");
      out.write("        }, 1000);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      // Open password modal when Download button is clicked\r\n");
      out.write("      document.getElementById(\"downloadBtn\").addEventListener(\"click\", function () {\r\n");
      out.write("        let passwordModal = new bootstrap.Modal(document.getElementById('passwordModal'));\r\n");
      out.write("        passwordModal.show();\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      // Handle password submission\r\n");
      out.write("      document.getElementById(\"submitPassword\").addEventListener(\"click\", function () {\r\n");
      out.write("        const correctPassword = \"exam123\"; // Set the correct password here\r\n");
      out.write("        const enteredPassword = document.getElementById(\"quizPassword\").value;\r\n");
      out.write("\r\n");
      out.write("        if (enteredPassword === correctPassword) {\r\n");
      out.write("          // Close modal\r\n");
      out.write("          let passwordModal = bootstrap.Modal.getInstance(document.getElementById('passwordModal'));\r\n");
      out.write("          passwordModal.hide();\r\n");
      out.write("\r\n");
      out.write("          // Simulate downloading exam paper\r\n");
      out.write("          alert(\"Exam paper downloaded!\");\r\n");
      out.write("\r\n");
      out.write("          // Clear any existing countdown\r\n");
      out.write("          clearInterval(countdownInterval);\r\n");
      out.write("\r\n");
      out.write("          // Start the countdown (e.g., 2 hours = 7200 seconds)\r\n");
      out.write("          startCountdown(7200); // 2 hours countdown\r\n");
      out.write("        } else {\r\n");
      out.write("          document.getElementById(\"errorMsg\").classList.remove(\"d-none\");\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
