/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-10-20 13:11:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class paymentupdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

String id=request.getParameter("id");
String name=request.getParameter("name");
String email=request.getParameter("email");
String address=request.getParameter("address");
String city=request.getParameter("city");
String state=request.getParameter("state");
String zipcode=request.getParameter("zipcode");
String cardname=request.getParameter("cardname");
String cardnumber=request.getParameter("cardnumber");
String expyear =request.getParameter("expyear");
String expmonth =request.getParameter("expmonth");
String cvv =request.getParameter("cvv");
String amount =request.getParameter("amount");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<form action=\"updateservlet\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                    <h3 class=\"title\">\r\n");
      out.write("                        user details\r\n");
      out.write("                    </h3>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"inputBox\">\r\n");
      out.write("                        <label for=\"name\">\r\n");
      out.write("                              Full Name:\r\n");
      out.write("                          </label>\r\n");
      out.write("                        <input type=\"text\" name=\"name\"  id=\"name\" value=\"");
      out.print(name);
      out.write("\"\r\n");
      out.write("                               placeholder=\"Enter your full name\" \r\n");
      out.write("                               required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"inputBox\">\r\n");
      out.write("                        <label for=\"email\">\r\n");
      out.write("                              Email:\r\n");
      out.write("                          </label>\r\n");
      out.write("                        <input type=\"text\" name=\"email\" \r\n");
      out.write("                               placeholder=\"Enter email address\" id=\"email\" value=\"");
      out.print(email);
      out.write("\"\r\n");
      out.write("                               required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"inputBox\">\r\n");
      out.write("                        <label for=\"address\">\r\n");
      out.write("                              Address:\r\n");
      out.write("                          </label>\r\n");
      out.write("                        <input type=\"text\" name=\"address\" id=\"address\"\r\n");
      out.write("                               placeholder=\"Enter address\" value=\"");
      out.print(address);
      out.write("\" \r\n");
      out.write("                               required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"inputBox\">\r\n");
      out.write("                        <label for=\"city\">\r\n");
      out.write("                              City:\r\n");
      out.write("                          </label>\r\n");
      out.write("                        <input type=\"text\" name=\"city\" id=\"city\"\r\n");
      out.write("                               placeholder=\"Enter city\" value=\"");
      out.print(city);
      out.write("\"\r\n");
      out.write("                               required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"flex\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"inputBox\">\r\n");
      out.write("                            <label for=\"state\">\r\n");
      out.write("                                  State:\r\n");
      out.write("                              </label>\r\n");
      out.write("                            <input type=\"text\" name=\"state\" id=\"state\"\r\n");
      out.write("                                   placeholder=\"Enter state\"  value=\"");
      out.print(state);
      out.write("\"\r\n");
      out.write("                                   required>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"inputBox\">\r\n");
      out.write("                            <label for=\"zip\">\r\n");
      out.write("                                  Zip Code:\r\n");
      out.write("                              </label>\r\n");
      out.write("                            <input type=\"number\" name=\"zipcode\" id=\"zipcode\"\r\n");
      out.write("                                   placeholder=\"123 456\" value=\"");
      out.print(zipcode);
      out.write("\"\r\n");
      out.write("                                   required>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                    <h3 class=\"title\">Payment</h3>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"inputBox\">\r\n");
      out.write("                        <label for=\"name\">\r\n");
      out.write("                              Card Accepted:\r\n");
      out.write("                          </label>\r\n");
      out.write("                  <img src=\"https://upload.wikimedia.org/wikipedia/commons/0/04/Visa.svg\" alt=\"Visa\" width=\"50px\">\r\n");
      out.write("                            <img src=\"https://upload.wikimedia.org/wikipedia/commons/b/b5/PayPal.svg\" alt=\"PayPal\" width=\"50px\">\r\n");
      out.write("                            <img src=\"https://upload.wikimedia.org/wikipedia/commons/a/a4/Mastercard_2019_logo.svg\" alt=\"MasterCard\" width=\"50px\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"inputBox\">\r\n");
      out.write("                        <label for=\"cardName\">\r\n");
      out.write("                              Name On Card:\r\n");
      out.write("                          </label>\r\n");
      out.write("                        <input type=\"text\" name=\"cardname\" id=\"cardname\"\r\n");
      out.write("                               placeholder=\"Enter card name\" value=\"");
      out.print(cardname);
      out.write("\"\r\n");
      out.write("                               required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"inputBox\">\r\n");
      out.write("                        <label for=\"cardNum\">\r\n");
      out.write("                              Credit Card Number:\r\n");
      out.write("                          </label>\r\n");
      out.write("                        <input type=\"text\" name=\"cardnumber\" id=\"cardnumber\"\r\n");
      out.write("                               placeholder=\"1111-2222-3333-4444\" \r\n");
      out.write("                               maxlength=\"19\" value=\"");
      out.print(cardnumber);
      out.write("\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"inputBox\">\r\n");
      out.write("    <label for=\"year\">Expire Year:</label>\r\n");
      out.write("    <select name=\"expyear\" id=\"expyear\" required>\r\n");
      out.write("        <option value=\"\" disabled >Select a year</option>\r\n");
      out.write("    \r\n");
      out.write("        <option value=\"2024\" ");
      out.print( expyear == "2024" ? "selected" : "" );
      out.write(">2024</option>\r\n");
      out.write("        <option value=\"2023\"");
      out.print( expyear == "2023" ? "selected" : "" );
      out.write(">2023</option>\r\n");
      out.write("        <option value=\"2022\"");
      out.print( expyear == "2022" ? "selected" : "" );
      out.write(">2022</option>\r\n");
      out.write("        <option value=\"2021\"");
      out.print( expyear == "2021" ? "selected" : "" );
      out.write(">2021</option>\r\n");
      out.write("        <option value=\"2020\"");
      out.print( expyear == "2020" ? "selected" : "" );
      out.write(">2020</option>\r\n");
      out.write("        <option value=\"2019\"");
      out.print( expyear == "2019" ? "selected" : "" );
      out.write(">2019</option>\r\n");
      out.write("         <option value=\"2018\"");
      out.print( expyear == "2018" ? "selected" : "" );
      out.write(">2018</option>\r\n");
      out.write("        <option value=\"2017\"");
      out.print( expyear == "2017" ? "selected" : "" );
      out.write(">2017</option>\r\n");
      out.write("        <option value=\"2016\"");
      out.print( expyear == "2016" ? "selected" : "" );
      out.write(">2016</option>\r\n");
      out.write(" \r\n");
      out.write("    </select>\r\n");
      out.write("</div>\r\n");
      out.write("               <div class=\"inputBox\">\r\n");
      out.write("    <label for=\"year\">Expire month:</label>\r\n");
      out.write("    <select name=\"expmonth\" id=\"expmonth\"  required>\r\n");
      out.write("        <option value=\"\" disabled>Select a month</option>\r\n");
      out.write("    \r\n");
      out.write("        <option value=\"january\" ");
      out.print( expmonth == "january" ? "selected" : "" );
      out.write(">January</option>\r\n");
      out.write("        <option value=\"february\"");
      out.print( expmonth =="february" ? "selected" : "" );
      out.write(">february</option>\r\n");
      out.write("        <option value=\"march\"");
      out.print( expmonth =="march" ? "selected" : "" );
      out.write(">march</option>\r\n");
      out.write("        <option value=\"april\"");
      out.print( expmonth =="april" ? "selected" : "" );
      out.write(">april</option>\r\n");
      out.write("        <option value=\"may\"");
      out.print( expmonth =="may" ? "selected" : "" );
      out.write(">may</option>\r\n");
      out.write("        <option value=\"june\"");
      out.print( expmonth =="june" ? "selected" : "" );
      out.write(">june</option>\r\n");
      out.write("         <option value=\"july\"");
      out.print( expmonth =="july" ? "selected" : "" );
      out.write(">july</option>\r\n");
      out.write("        <option value=\"august\"");
      out.print( expmonth =="august" ? "selected" : "" );
      out.write(">august</option>\r\n");
      out.write("        <option value=\"september\"");
      out.print( expmonth =="september" ? "selected" : "" );
      out.write(">september</option>\r\n");
      out.write("        <option value=\"october\"");
      out.print( expmonth =="october" ? "selected" : "" );
      out.write(">october</option>\r\n");
      out.write("        <option value=\"november\"");
      out.print( expmonth =="november" ? "selected" : "" );
      out.write(">november</option>\r\n");
      out.write("        <option value=\"december\"");
      out.print( expmonth =="december" ? "selected" : "" );
      out.write(">december</option>\r\n");
      out.write(" \r\n");
      out.write("    </select>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" <div class=\"inputBox\">\r\n");
      out.write("                        <label for=\"cvv\">\r\n");
      out.write("                              cvv:\r\n");
      out.write("                          </label>\r\n");
      out.write("                        <input type=\"text\" name=\"cvv\" id=\"cvv\"\r\n");
      out.write("                               placeholder=\"Enter cvv\" value=\"");
      out.print(cvv);
      out.write("\"\r\n");
      out.write("                               required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("   <div class=\"inputBox\">\r\n");
      out.write("                        <label for=\"cvv\">\r\n");
      out.write("                              amount:\r\n");
      out.write("                          </label>\r\n");
      out.write("                        <input type=\"text\" name=\"amount\" id=\"amount\"\r\n");
      out.write("                               placeholder=\"Enter amount\" value=\"");
      out.print(amount);
      out.write("\"\r\n");
      out.write("                               required>\r\n");
      out.write("                    </div>                  \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                       <input type=\"submit\" value=\"save\" \r\n");
      out.write("                   class=\"submit_btn\">\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
